import test from 'node:test';
import assert from 'node:assert/strict';
import { lessons } from '../public/curriculum.js';
import { complete, review, dueLessons, DAY } from '../public/progress.js';
import { createApp } from '../server.mjs';
test('90 unique bilingual lessons, 30 per month',()=>{assert.equal(lessons.length,90);assert.equal(new Set(lessons.map(l=>l.ko)).size,90);for(const l of lessons)assert.ok(l.ja&&l.en&&l.ko);for(const m of [1,2,3])assert.equal(lessons.filter(l=>l.month===m).length,30);});
test('review schedule, retry and duplicate completion preserve progress',()=>{let r=complete({},1,0);assert.equal(dueLessons(lessons,r,DAY-1).length,0);assert.equal(dueLessons(lessons,r,DAY).length,1);assert.deepEqual(complete(r,1,DAY),r);r=review(r,1,true,DAY);assert.equal(r[1].due,4*DAY);r=review(r,1,true,4*DAY);assert.equal(r[1].due,11*DAY);r=review(r,1,false,11*DAY);assert.equal(r[1].due,12*DAY);assert.equal(r[1].stage,0);assert.deepEqual(review({},1,true),{});});
async function withServer(options,fn){const server=createApp(options);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{await fn(`http://127.0.0.1:${server.address().port}`);}finally{await new Promise(resolve=>server.close(resolve));}}
test('static allowlist hides server and secrets; demo is explicit',()=>withServer({apiKey:''},async base=>{assert.equal((await fetch(base)).status,200);assert.deepEqual(await(await fetch(base+'/api/config')).json(),{ai:false});for(const p of ['/.env','/server.mjs','/.git/config'])assert.equal((await fetch(base+p)).status,404);assert.equal((await fetch(base+'/api/chat',{method:'POST'})).status,503);}));
test('AI validation, server-side key, context and response extraction',()=>withServer({apiKey:'test-key',fetchImpl:async(url,init)=>{assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(init.headers.Authorization,'Bearer test-key');const body=JSON.parse(init.body);assert.equal(body.store,false);assert.equal(body.input[0].content,'Hello');assert.match(body.instructions,/English/);return {ok:true,json:async()=>({output:[{type:'reasoning'},{content:[{type:'output_text',text:'Hello!'}]}]})};}},async base=>{const send=data=>fetch(base+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});assert.equal((await send({})).status,400);assert.equal((await send(null)).status,400);assert.equal((await send({language:'en',lessonId:1,messages:[{role:'system',content:'bad'}]})).status,400);const r=await send({language:'en',lessonId:1,messages:[{role:'user',content:'Hello'}]});assert.equal(r.status,200);assert.deepEqual(await r.json(),{reply:'Hello!'});}));
